services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    networks:
      - jenkins_network
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent storage for Jenkins data
      - /Users/kraipobsaengkhunthod/.docker/run/docker.sock:/var/run/docker.sock  # Custom Docker socket path
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock  # Make Docker available to Jenkins
    privileged: true  # Required for Docker in Docker (optional but sometimes needed)

volumes:
  jenkins_home:

networks:
  jenkins_network:
    driver: bridge
    external: true
